#server configuration
server.port=8080
server.servlet.context-path=/
#spring configs
spring.application.name=find-ip-detector

#log configs
logging.level.com.br.rafaelsindice.ipdescovery=debug
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

#actuator endpoints 
management.endpoints.web.exposure.include=health,info
#config ip detection headers
#trus X-forwwarded quando está por tras de proxy
server.forward-headers-strategy=native

#auto save
spring.devtools.restart.enabled=true